# Generated by Django 4.1.2 on 2022-10-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Дата и время',
            new_name='dateTime',
        ),
    ]
